type Review = { id: string; user: string; comment: string };
type Product = {
  id: number;
  description: string;
  category: string;
  brand: string;
  condition: string;
  inventNum: number;
  soldNum: number;
  currentPrice: number;
  originalPrice: number;
  imgUrl: string;
  isWishlisted: boolean;
  reviews?: Review[];
};

export const mockProductData: Product[] = [
  {
    id: 1,
    description: "Introduction to Algorithms textbook",
    category: "Text Books",
    brand: "MIT Press",
    condition: "Used",
    inventNum: 5,
    soldNum: 2,
    currentPrice: 45,
    originalPrice: 80,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 2,
    description: "iPhone 12 64GB",
    category: "Electronics",
    brand: "Apple",
    condition: "Excellent",
    inventNum: 3,
    soldNum: 1,
    currentPrice: 600,
    originalPrice: 800,
    imgUrl: "https://picsum.photos",
    isWishlisted: true,
    reviews: [
      {
        id: "a7b8c9d0-1234-5678-9abc-def012345678",
        user: "Alice",
        comment: "Great phone!",
      },
      {
        id: "a7b8c9d0-1234-5678-9abc-def012345690",
        user: "Bob",
        comment: "A little expensive, could it be a little cheaper?",
      },
    ],
  },
  {
    id: 3,
    description: "Samsung Galaxy Buds Pro",
    category: "Electronics",
    brand: "Samsung",
    condition: "Excellent",
    inventNum: 4,
    soldNum: 0,
    currentPrice: 100,
    originalPrice: 150,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 4,
    description: "Wooden study desk",
    category: "Furniture",
    brand: "IKEA",
    condition: "Good",
    inventNum: 2,
    soldNum: 0,
    currentPrice: 70,
    originalPrice: 120,
    imgUrl: "https://picsum.photos",
    isWishlisted: true,
  },
  {
    id: 5,
    description: "Mountain bike",
    category: "Vehicles",
    brand: "Giant",
    condition: "Used",
    inventNum: 1,
    soldNum: 0,
    currentPrice: 200,
    originalPrice: 500,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 6,
    description: "Denim jacket",
    category: "Clothes",
    brand: "Levi's",
    condition: "Very Good",
    inventNum: 5,
    soldNum: 1,
    currentPrice: 40,
    originalPrice: 80,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 7,
    description: "Wireless mouse",
    category: "Electronics",
    brand: "Logitech",
    condition: "New",
    inventNum: 6,
    soldNum: 0,
    currentPrice: 25,
    originalPrice: 40,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 8,
    description: "Data Structures textbook",
    category: "Text Books",
    brand: "Pearson",
    condition: "Used",
    inventNum: 3,
    soldNum: 2,
    currentPrice: 35,
    originalPrice: 70,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 9,
    description: "Office chair",
    category: "Furniture",
    brand: "IKEA",
    condition: "Very Good",
    inventNum: 2,
    soldNum: 0,
    currentPrice: 60,
    originalPrice: 120,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 10,
    description: "Leather backpack",
    category: "Clothes",
    brand: "Fossil",
    condition: "Excellent",
    inventNum: 4,
    soldNum: 1,
    currentPrice: 80,
    originalPrice: 150,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 11,
    description: "MacBook Pro 2019",
    category: "Electronics",
    brand: "Apple",
    condition: "Open box",
    inventNum: 2,
    soldNum: 0,
    currentPrice: 1200,
    originalPrice: 1800,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 12,
    description: "Calculus textbook",
    category: "Text Books",
    brand: "McGraw-Hill",
    condition: "Good",
    inventNum: 5,
    soldNum: 3,
    currentPrice: 30,
    originalPrice: 60,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 13,
    description: "Gaming keyboard",
    category: "Electronics",
    brand: "Razer",
    condition: "Very Good",
    inventNum: 3,
    soldNum: 0,
    currentPrice: 80,
    originalPrice: 130,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 14,
    description: "Electric guitar",
    category: "Electronics",
    brand: "Yamaha",
    condition: "Used",
    inventNum: 1,
    soldNum: 0,
    currentPrice: 250,
    originalPrice: 500,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 15,
    description: "Science Fiction novel",
    category: "Text Books",
    brand: "Penguin",
    condition: "New",
    inventNum: 10,
    soldNum: 2,
    currentPrice: 12,
    originalPrice: 25,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 16,
    description: "Study lamp",
    category: "Furniture",
    brand: "Philips",
    condition: "New",
    inventNum: 5,
    soldNum: 0,
    currentPrice: 20,
    originalPrice: 40,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 17,
    description: "Bicycle helmet",
    category: "Clothes",
    brand: "Giro",
    condition: "Excellent",
    inventNum: 3,
    soldNum: 1,
    currentPrice: 35,
    originalPrice: 60,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 18,
    description: "Portable hard drive 1TB",
    category: "Electronics",
    brand: "Seagate",
    condition: "Good",
    inventNum: 6,
    soldNum: 2,
    currentPrice: 45,
    originalPrice: 80,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 19,
    description: "Winter coat",
    category: "Clothes",
    brand: "North Face",
    condition: "Used",
    inventNum: 4,
    soldNum: 1,
    currentPrice: 60,
    originalPrice: 200,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
  {
    id: 20,
    description: "Used car - Honda Civic 2010",
    category: "Vehicles",
    brand: "Honda",
    condition: "For parts not working",
    inventNum: 1,
    soldNum: 0,
    currentPrice: 1500,
    originalPrice: 8000,
    imgUrl: "https://picsum.photos",
    isWishlisted: false,
  },
];
