export const brandCategoryMap = {
  "Electronics": ["Sony", "Panasonic", "LG", "Philips", "Bose", "Seagate"],
  "Phones": ["Apple", "Samsung", "Google", "Huawei", "OnePlus"],
  "Computers": ["Dell", "HP", "Lenovo", "Asus", "Acer"],
  "Tech Accessories": ["Logitech", "Anker", "Belkin", "Razer", "Kingston"],
  "Text Books": ["Pearson", "McGraw-Hill", "Oxford University Press", "Cengage", "Springer", "MIT Press"],
  "Fiction Books": ["Penguin Random House", "HarperCollins", "Simon & Schuster", "Hachette"],
  "Furniture": ["IKEA", "Ashley Furniture", "Wayfair", "La-Z-Boy"],
  "Home Decor": ["Pottery Barn", "Crate & Barrel", "West Elm", "Anthropologie"],
  "Appliances": ["Whirlpool", "GE", "Bosch", "KitchenAid", "Samsung Appliances"],
  "Vehicles": ["Toyota", "Honda", "Ford", "BMW", "Mercedes-Benz", "Giant"],
  "Vehicle Parts": ["Bosch Auto", "Michelin", "Goodyear", "Bridgestone", "Denso"],
  "Clothes": ["Levi's", "Zara", "H&M", "Gap", "Uniqlo", "North Face"],
  "Shoes": ["Nike", "Adidas", "Puma", "Reebok", "Converse"],
  "Bags": ["Coach", "Michael Kors", "Louis Vuitton", "Herschel", "Fossil"],
  "Sports Gear": ["Wilson", "Spalding", "Under Armour", "Decathlon", "Giro"],
  "Musical Instruments": ["Yamaha", "Fender", "Gibson", "Roland", "Steinway"],
  "Art Supplies": ["Winsor & Newton", "Faber-Castell", "Prismacolor", "Copic"],
  "Toys": ["LEGO", "Mattel", "Hasbro", "Playmobil", "Nerf"],
  "Baby Items": ["Pampers", "Huggies", "Fisher-Price", "Chicco", "Graco"],
  "Pet Supplies": ["Purina", "Pedigree", "Kong", "PetSafe", "Blue Buffalo"],
  "Services": ["TaskRabbit", "Angi", "Thumbtack", "Fiverr", "Upwork"],
  "Others": ["AmazonBasics", "Generic", "Local Brand"],
};