import type { Seller } from "@prisma/client"

export const sellersData: Omit<Seller, "id" | "createdAt" | "updatedAt">[] = [
  { username: "TechTrader01",  rating: 92, completedSales: 23, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=TechTrader01" },
  { username: "VintageFinds",  rating: 87, completedSales: 19, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=VintageFinds" },
  { username: "GameStopper",   rating: 95, completedSales: 25, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GameStopper" },
  { username: "EcoClothes",    rating: 90, completedSales: 16, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=EcoClothes" },
  { username: "BookBarn",      rating: 85, completedSales: 12, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=BookBarn" },
  { username: "CraftyCorner",  rating: 93, completedSales: 21, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=CraftyCorner" },
  { username: "RetroGadget",   rating: 89, completedSales: 18, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=RetroGadget" },
  { username: "ToyBoxX",       rating: 80, completedSales: 11, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ToyBoxX" },
  { username: "SneakerHub",    rating: 97, completedSales: 24, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SneakerHub" },
  { username: "GreenThumb",    rating: 88, completedSales: 14, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GreenThumb" },
  { username: "PixelParts",    rating: 91, completedSales: 22, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PixelParts" },
  { username: "ModernMaker",   rating: 83, completedSales: 15, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ModernMaker" },
  { username: "HomeHaven",     rating: 94, completedSales: 28, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=HomeHaven" },
  { username: "GadgetGuru",    rating: 96, completedSales: 30, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GadgetGuru" },
  { username: "RetroRack",     rating: 84, completedSales: 17, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=RetroRack" },
  { username: "CozyCrafts",    rating: 90, completedSales: 20, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=CozyCrafts" },
  { username: "UrbanStyle",    rating: 88, completedSales: 26, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=UrbanStyle" },
  { username: "PetParadise",   rating: 82, completedSales: 13, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PetParadise" },
  { username: "BrewBuddy",     rating: 89, completedSales: 19, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=BrewBuddy" },
  { username: "SmartHomeShop", rating: 95, completedSales: 32, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SmartHomeShop" },
  { username: "OutdoorOasis",  rating: 86, completedSales: 15, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=OutdoorOasis" },
  { username: "ArtisanAlley",  rating: 91, completedSales: 27, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ArtisanAlley" },
  { username: "SoundWave",     rating: 93, completedSales: 29, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SoundWave" },
  { username: "SmartThreads",  rating: 88, completedSales: 18, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SmartThreads" },
  { username: "PixelPets",     rating: 90, completedSales: 22, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PixelPets" },
];
