// sellers.data.ts
export const sellersData = [
  { id: 1,  username: "TechTrader01",  rating: 92, completedSales: 23, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=TechTrader01" },
  { id: 2,  username: "VintageFinds",  rating: 87, completedSales: 19, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=VintageFinds" },
  { id: 3,  username: "GameStopper",   rating: 95, completedSales: 25, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GameStopper" },
  { id: 4,  username: "EcoClothes",    rating: 90, completedSales: 16, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=EcoClothes" },
  { id: 5,  username: "BookBarn",      rating: 85, completedSales: 12, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=BookBarn" },
  { id: 6,  username: "CraftyCorner",  rating: 93, completedSales: 21, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=CraftyCorner" },
  { id: 7,  username: "RetroGadget",   rating: 89, completedSales: 18, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=RetroGadget" },
  { id: 8,  username: "ToyBoxX",       rating: 80, completedSales: 11, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ToyBoxX" },
  { id: 9,  username: "SneakerHub",    rating: 97, completedSales: 24, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SneakerHub" },
  { id: 10, username: "GreenThumb",    rating: 88, completedSales: 14, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GreenThumb" },
  { id: 11, username: "PixelParts",    rating: 91, completedSales: 22, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PixelParts" },
  { id: 12, username: "ModernMaker",   rating: 83, completedSales: 15, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ModernMaker" },
  { id: 13, username: "HomeHaven",     rating: 94, completedSales: 28, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=HomeHaven" },
  { id: 14, username: "GadgetGuru",    rating: 96, completedSales: 30, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=GadgetGuru" },
  { id: 15, username: "RetroRack",     rating: 84, completedSales: 17, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=RetroRack" },
  { id: 16, username: "CozyCrafts",    rating: 90, completedSales: 20, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=CozyCrafts" },
  { id: 17, username: "UrbanStyle",    rating: 88, completedSales: 26, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=UrbanStyle" },
  { id: 18, username: "PetParadise",   rating: 82, completedSales: 13, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PetParadise" },
  { id: 19, username: "BrewBuddy",     rating: 89, completedSales: 19, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=BrewBuddy" },
  { id: 20, username: "SmartHomeShop", rating: 95, completedSales: 32, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SmartHomeShop" },
  { id: 21, username: "OutdoorOasis",  rating: 86, completedSales: 15, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=OutdoorOasis" },
  { id: 22, username: "ArtisanAlley",  rating: 91, completedSales: 27, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=ArtisanAlley" },
  { id: 23, username: "SoundWave",     rating: 93, completedSales: 29, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SoundWave" },
  { id: 24, username: "SmartThreads",  rating: 88, completedSales: 18, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=SmartThreads" },
  { id: 25, username: "PixelPets",     rating: 90, completedSales: 22, photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=PixelPets" },
];
